# Generated by Django 3.0.4 on 2020-03-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('erntehelfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, 'Offen'), (1, 'Bestätigt'), (2, 'Abgelehnt')], default=0)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erntehelfer.CitizenProfile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Interessensangebot',
                'verbose_name_plural': 'Interessensangebote',
            },
        ),
    ]
