# Generated by Django 3.0.4 on 2020-03-28 22:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erntehelfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kurz zusammengefasst um was es geht', max_length=250, verbose_name='Stellenbeschreibung')),
                ('description', models.TextField(help_text='Ausführliche Beschreibung der Tätigkeiten oder weitere Details', verbose_name='Beschreibung des Angebots')),
                ('helpers_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='Anzahl der benötigten Helfer')),
                ('zip_code', models.CharField(max_length=16, verbose_name='Postleitzahl')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('start_date', models.DateField(verbose_name='Arbeitsbeginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('done', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Category', verbose_name='Kategorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erntehelfer.CompanyProfile')),
                ('drivers_licenses', models.ManyToManyField(blank=True, help_text='Führerscheinklassen, die zur Ausführung der Arbeit erforderlich sind', to='erntehelfer.LicenseClass', verbose_name='Führerscheinklassen')),
            ],
            options={
                'verbose_name': 'Inserat',
                'verbose_name_plural': 'Inserate',
            },
        ),
        migrations.CreateModel(
            name='TaskOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='Vollständiger Name')),
                ('date_of_birth', models.DateField(verbose_name='Geburtsdatum')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail Adresse')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefonnummer')),
                ('message', models.TextField(max_length=500, verbose_name='Nachricht an den Betrieb')),
                ('state', models.IntegerField(choices=[(0, 'Offen'), (1, 'Akzeptiert'), (2, 'Abgelehnt')], default=0)),
                ('drivers_licenses', models.ManyToManyField(blank=True, to='erntehelfer.LicenseClass', verbose_name='Führerscheinklassen')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Bewerbung',
                'verbose_name_plural': 'Bewerbungen',
            },
        ),
    ]
