# Generated by Django 3.0.4 on 2020-03-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0001_initial'),
        ('tasks', '0002_auto_20200324_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Beschreibung des Angebots'),
        ),
        migrations.AlterField(
            model_name='task',
            name='drivers_licenses',
            field=models.ManyToManyField(blank=True, to='erntehelfer.LicenseClass', verbose_name='Führerscheinklassen'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(verbose_name='Beginn'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='task',
            name='zip_code',
            field=models.CharField(max_length=16, verbose_name='Postleitzahl'),
        ),
    ]
