# Generated by Django 3.0.4 on 2020-03-26 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_helpers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='helpers_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='Benötigte Helfer'),
        ),
    ]
