# Generated by Django 3.0.4 on 2020-03-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0003_auto_20200326_2019'),
        ('tasks', '0005_auto_20200326_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Inserat', 'verbose_name_plural': 'Inserate'},
        ),
        migrations.CreateModel(
            name='TaskOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='Vollständiger Name')),
                ('date_of_birth', models.DateField(verbose_name='Geburtsdatum')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail Adresse')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefonnummer')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('state', models.IntegerField(choices=[(0, 'Offen'), (1, 'Akzeptiert'), (2, 'Abgelehnt')], default=0)),
                ('drivers_licenses', models.ManyToManyField(blank=True, to='erntehelfer.LicenseClass', verbose_name='Führerscheinklassen')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Bewerbung',
                'verbose_name_plural': 'Bewerbungen',
            },
        ),
    ]
