# Generated by Django 3.0.4 on 2020-03-28 07:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0004_auto_20200328_0831'),
        ('tasks', '0006_auto_20200326_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Ausführliche Beschreibung der Tätigkeiten oder weitere Details', verbose_name='Beschreibung des Angebots'),
        ),
        migrations.AlterField(
            model_name='task',
            name='drivers_licenses',
            field=models.ManyToManyField(blank=True, help_text='Führerscheinklassen, die zur Ausführung der Arbeit erforderlich sind', to='erntehelfer.LicenseClass', verbose_name='Führerscheinklassen'),
        ),
        migrations.AlterField(
            model_name='task',
            name='helpers_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='Anzahl der benötigten Helfer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(verbose_name='Arbeitsbeginn'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Kurz zusammengefasst um was es geht', max_length=250, verbose_name='Stellenbeschreibung'),
        ),
        migrations.AlterField(
            model_name='taskoffer',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Nachricht an den Betrieb'),
        ),
        migrations.AlterField(
            model_name='taskoffer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
