# Generated by Django 3.0.4 on 2020-03-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
