# Generated by Django 3.0.4 on 2020-03-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erntehelfer.CompanyProfile'),
        ),
    ]
