# Generated by Django 3.0.4 on 2020-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0002_auto_20200326_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
