# Generated by Django 3.0.4 on 2020-03-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0003_auto_20200326_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=250, verbose_name='Betriebsname'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Betriebsnummer'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung über den Betrieb'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Straße und Hausnummer'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Postleitzahl'),
        ),
    ]
