# Generated by Django 3.0.4 on 2020-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0003_auto_20200321_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
