# Generated by Django 3.0.4 on 2020-03-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0008_interestoffers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestOffers',
            new_name='InterestOffer',
        ),
    ]
