# Generated by Django 3.0.4 on 2020-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erntehelfer', '0009_auto_20200322_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestoffer',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
